name: Dynamic Secrets 

on: workflow_dispatch


jobs:
  example:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        s: [1, 2]

    steps:
      - name: Output secret
        run: |
          echo "Value of SECRET_${{ matrix.s }}:"
          echo "'${{ secrets[format('SECRET_{0}', matrix.s)] }}'" | rev
