name: dynamic jobs

on:
  workflow_dispatch:
    inputs:
      values:            

jobs:
  work:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        id: ${{ fromJson( github.event.inputs.values ) }}
  
    name: ${{ matrix.id }}
    
    steps:
      - run: echo "hello world"
        
