name: dynamic jobs

on:
  workflow_dispatch:


jobs:
  dice:
    runs-on: ubuntu-latest
    
    outputs:
      sum:
        description: 'Number of jobs to run'
        
  work:
    strategy:
      matrix:
        
