name: Secrets example

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  repo-secret:
    runs-on: ubuntu-latest

    steps:         
      # This will output the secret defined at the env level
      - run: echo ${{ secrets.SECRET }} | rev

  env-secret:
    runs-on: ubuntu-latest
    
    environment: secrets-env

    steps:     
      # This will output the secret defined at the env level
      - run: echo ${{ secrets.SECRET }} | rev
